-- migrations/012_create_news_articles.sql
-- Admin News management table

BEGIN;

CREATE TABLE IF NOT EXISTS public.news_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL CHECK (category IN ('COLLECTION', 'EVENT', 'COLLABORATION', 'SUSTAINABILITY', 'STORE')),
  published_date date NOT NULL,
  image_url text NOT NULL,
  content text NOT NULL,
  detailed_content text NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'published')) DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS news_articles_published_date_idx ON public.news_articles (published_date DESC);
CREATE INDEX IF NOT EXISTS news_articles_status_idx ON public.news_articles (status);
CREATE INDEX IF NOT EXISTS news_articles_category_idx ON public.news_articles (category);

CREATE OR REPLACE FUNCTION public.set_news_articles_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_news_articles_updated_at ON public.news_articles;
CREATE TRIGGER trg_news_articles_updated_at
  BEFORE UPDATE ON public.news_articles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_news_articles_updated_at();

COMMENT ON TABLE public.news_articles IS 'News articles managed from admin UI';

COMMIT;
