-- migrations/017_create_item_color_presets.sql
-- Persistent color presets for admin item create/edit

BEGIN;

CREATE TABLE IF NOT EXISTS public.item_color_presets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  hex text NOT NULL CHECK (hex ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_color_presets_name_hex_key UNIQUE (name, hex)
);

ALTER TABLE public.item_color_presets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role has full access to item color presets" ON public.item_color_presets;
CREATE POLICY "Service role has full access to item color presets"
ON public.item_color_presets
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

COMMIT;
