-- migrations/018_create_looks_and_look_images_bucket.sql
-- Admin look create support (table + relation + storage bucket + RLS)

BEGIN;

CREATE TABLE IF NOT EXISTS public.looks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_year integer NOT NULL CHECK (season_year >= 2000 AND season_year <= 2100),
  season_type text NOT NULL CHECK (season_type IN ('SS', 'AW')),
  theme text NOT NULL,
  theme_description text NOT NULL DEFAULT '',
  image_urls text[] NOT NULL DEFAULT '{}',
  status text NOT NULL CHECK (status IN ('private', 'published')) DEFAULT 'private',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.look_items (
  look_id bigint NOT NULL REFERENCES public.looks (id) ON DELETE CASCADE,
  item_id bigint NOT NULL REFERENCES public.items (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (look_id, item_id)
);

CREATE INDEX IF NOT EXISTS looks_created_at_idx ON public.looks (created_at DESC);
CREATE INDEX IF NOT EXISTS looks_status_idx ON public.looks (status);
CREATE INDEX IF NOT EXISTS look_items_item_id_idx ON public.look_items (item_id);

CREATE OR REPLACE FUNCTION public.set_looks_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_looks_updated_at ON public.looks;
CREATE TRIGGER trg_looks_updated_at
  BEFORE UPDATE ON public.looks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_looks_updated_at();

ALTER TABLE public.looks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.look_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view published looks" ON public.looks;
CREATE POLICY "Anyone can view published looks"
ON public.looks
FOR SELECT
USING (status = 'published');

DROP POLICY IF EXISTS "Service role has full access to looks" ON public.looks;
CREATE POLICY "Service role has full access to looks"
ON public.looks
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Service role has full access to look items" ON public.look_items;
CREATE POLICY "Service role has full access to look items"
ON public.look_items
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
SELECT
  'look-images',
  'look-images',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
WHERE NOT EXISTS (
  SELECT 1 FROM storage.buckets WHERE id = 'look-images'
);

COMMIT;
