import { test, expect } from '@playwright/test';

test.describe('FR-HOME-006 home metadata', () => {
  test('home page has specific title and description metadata', async ({ page }) => {
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    const title = await page.title();
    expect(title).toBeTruthy();
    expect(title.toLowerCase()).not.toContain('create next app');

    const description = await page.locator('head meta[name="description"]').getAttribute('content');
    expect(description).toBeTruthy();
    expect(description?.toLowerCase()).not.toContain('generated by create next app');
  });
});
