import type { Metadata } from "next"; // Metadata型をNext.jsからインポート
import { Geist, Geist_Mono } from "next/font/google"; // Google FontsのGeistとGeist_Monoフォントをインポート
import "./globals.css"; // グローバルCSSファイルをインポート
import Header from './components/Header'; // ヘッダーコンポーネントをインポート
import Footer from './components/Footer'; // フッターコンポーネントをインポート
import { LoginProvider } from './components/LoginContext'; // ログイン状態管理のためのLoginProviderをインポート

// Geistフォントを設定。変数名を`--font-geist-sans`に設定。
const geistSans = Geist({
  variable: "--font-geist-sans",  // カスタムCSS変数を使用してフォントを管理
  subsets: ["latin"],  // 使用する文字セット（ここではラテン文字）
});

// Geist_Monoフォントを設定。変数名を`--font-geist-mono`に設定。
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // カスタムCSS変数を使用してモノスペースフォントを管理
  subsets: ["latin"],  // 使用する文字セット（ここではラテン文字）
});

// ページ全体のメタデータを定義
export const metadata: Metadata = {
  title: "O | Official Web Site",  // ページのタイトル
  description: "Generated by create next app",  // ページの説明
};

// RootLayoutコンポーネントをエクスポート
export default function RootLayout({
  children,  // `children`はレイアウト内に挿入されるコンテンツ（子コンポーネント）を示す
}: Readonly<{
  children: React.ReactNode;  // childrenはReactのノード（要素、文字列など）であることを示す
}>) {
  return (
    // <html>タグでページ全体をラップ
    <html lang="ja">  {/* ページの言語を英語に設定 */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`} > {/* BodyにフォントのCSS変数と`antialiased`（アンチエイリアス効果）を適用*/}
        <LoginProvider>
          <Header /> {/* ヘッダーを表示する */}
          <div className="flex-1">
            {children}{/* 各ページのコンテンツが表示される部分。childrenに渡されたコンテンツがここに挿入される */}
          </div>
          <Footer /> {/* フッターを表示する */}
        </LoginProvider>
      </body>
    </html>
  );
}
