import type { Metadata } from "next"; // Metadata型をNext.jsからインポート
import { headers } from 'next/headers';
import { Geist, Geist_Mono } from "next/font/google"; // Google FontsのGeistとGeist_Monoフォントをインポート
import "./globals.css"; // グローバルCSSファイルをインポート
import Header from './components/Header'; // ヘッダーコンポーネントをインポート
import Footer from './components/Footer'; // フッターコンポーネントをインポート
import { LoginProvider } from './components/LoginContext'; // ログイン状態管理のためのLoginProviderをインポート

// Geistフォントを設定。変数名を`--font-geist-sans`に設定。
const geistSans = Geist({
  variable: "--font-geist-sans",  // カスタムCSS変数を使用してフォントを管理
  subsets: ["latin"],  // 使用する文字セット（ここではラテン文字）
});

// Geist_Monoフォントを設定。変数名を`--font-geist-mono`に設定。
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // カスタムCSS変数を使用してモノスペースフォントを管理
  subsets: ["latin"],  // 使用する文字セット（ここではラテン文字）
});

// ページ全体のメタデータを定義
export const metadata: Metadata = {
  title: "O | Official Web Site",  // ページのタイトル
  description: "Generated by create next app",  // ページの説明
};

// RootLayoutコンポーネントをエクスポート
export default async function RootLayout({
  children,  // `children`はレイアウト内に挿入されるコンテンツ（子コンポーネント）を示す
}: Readonly<{
  children: React.ReactNode;  // childrenはReactのノード（要素、文字列など）であることを示す
}>) {
  const nonce = (await headers()).get('x-nonce') ?? undefined;

  return (
    <html lang="ja">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css" />
        <script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer nonce={nonce}></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}> 
        <LoginProvider>
          <Header />
          <div className="flex-1 flex flex-col"> {/* Bodyの高さを調整し、Footerが常に下に来るように */}
            {children}
          </div>
          <Footer />
        </LoginProvider>
      </body>
    </html>
  );
}
