-- 在庫台帳。在庫は台帳への追記でしか動かせないようにし、
-- アプリケーションが台帳を書き忘れることを構造的に不可能にする。

BEGIN;

CREATE TABLE public.stock_movements (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id    bigint NOT NULL REFERENCES public.item_variants(id) ON DELETE RESTRICT,
  delta         integer NOT NULL CHECK (delta <> 0),
  reason        text    NOT NULL CHECK (reason IN
                  ('purchase','restock','adjustment','cancel','refund')),
  order_id      uuid REFERENCES public.orders(id) ON DELETE SET NULL,
  order_item_id uuid REFERENCES public.order_items(id) ON DELETE SET NULL,
  note          text,
  created_by    uuid REFERENCES public.profiles(user_id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX stock_movements_variant_id_idx ON public.stock_movements (variant_id);
CREATE INDEX stock_movements_order_id_idx   ON public.stock_movements (order_id);

-- 台帳の追記をバリアントの在庫へ反映する。
-- item_variants.stock_quantity の CHECK (>= 0) が在庫不足の最終防衛線になる。
CREATE OR REPLACE FUNCTION public.apply_stock_movement()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  UPDATE public.item_variants
  SET stock_quantity = stock_quantity + NEW.delta,
      updated_at     = now()
  WHERE id = NEW.variant_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER stock_movements_apply
  AFTER INSERT ON public.stock_movements
  FOR EACH ROW EXECUTE FUNCTION public.apply_stock_movement();

-- 追記専用の強制。権限だけでなくトリガーでも止める（service role は権限を迂回できるため）。
CREATE OR REPLACE FUNCTION public.reject_stock_movement_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'stock_movements is append-only';
END;
$$;

CREATE TRIGGER stock_movements_no_update
  BEFORE UPDATE ON public.stock_movements
  FOR EACH ROW EXECUTE FUNCTION public.reject_stock_movement_mutation();

CREATE TRIGGER stock_movements_no_delete
  BEFORE DELETE ON public.stock_movements
  FOR EACH ROW EXECUTE FUNCTION public.reject_stock_movement_mutation();

-- TRUNCATE は RLS も行レベルトリガーも通らないため、文レベルのトリガーで止める。
-- reject_stock_movement_mutation() は NEW / OLD を参照しないので文トリガーからも使える。
CREATE TRIGGER stock_movements_no_truncate
  BEFORE TRUNCATE ON public.stock_movements
  FOR EACH STATEMENT EXECUTE FUNCTION public.reject_stock_movement_mutation();

ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deny direct client access" ON public.stock_movements
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);

-- このプロジェクトの Supabase は public スキーマの新規テーブルとそのシーケンスに
-- anon / authenticated へ全権限を自動付与するため、まず剥がす。
-- シーケンスの ACL はテーブルとは別オブジェクトなので個別に指定する。
REVOKE ALL ON public.stock_movements FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.stock_movements_id_seq FROM anon, authenticated;

-- GRANT は自動付与された権限を狭めないので、まず剥がしてから必要な分だけ付け直す。
REVOKE ALL ON public.stock_movements FROM service_role;

GRANT SELECT, INSERT ON public.stock_movements TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.stock_movements_id_seq TO service_role;

COMMIT;
