-- サイズ × カラーのバリアントを在庫の単位にするためのテーブル群。
-- 既存の items.colors / items.sizes / items.stock_quantity はこの時点では残す
-- （アプリケーションの切り替えが終わったあと、後続のマイグレーションで削除する）。

BEGIN;

CREATE TABLE public.item_colors (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id  bigint NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  name     text   NOT NULL,
  hex      text   NOT NULL CHECK (hex ~ '^#[0-9a-fA-F]{6}$'),
  position integer NOT NULL DEFAULT 0,
  UNIQUE (item_id, name)
);
CREATE INDEX item_colors_item_id_idx ON public.item_colors (item_id);

-- position が表示順の真実。コード側の SIZE_ORDER ハードコードはこれに置き換える。
CREATE TABLE public.item_sizes (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id  bigint NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  label    text   NOT NULL,
  position integer NOT NULL DEFAULT 0,
  UNIQUE (item_id, label)
);
CREATE INDEX item_sizes_item_id_idx ON public.item_sizes (item_id);

CREATE TABLE public.item_variants (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id        bigint NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  color_id       bigint REFERENCES public.item_colors(id) ON DELETE RESTRICT,
  size_id        bigint REFERENCES public.item_sizes(id)  ON DELETE RESTRICT,
  sku            text UNIQUE,
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_active      boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX item_variants_item_id_idx ON public.item_variants (item_id);

-- NULL を含む UNIQUE 制約は Postgres では重複を許すため、式インデックスで一意性を担保する。
CREATE UNIQUE INDEX item_variants_combo_key
  ON public.item_variants (item_id, coalesce(color_id, 0), coalesce(size_id, 0));

-- 受注時のお届け目安（商品単位）。在庫切れの組み合わせの表示に使う。
ALTER TABLE public.items
  ADD COLUMN made_to_order_lead_days integer
    CHECK (made_to_order_lead_days IS NULL OR made_to_order_lead_days >= 0);

ALTER TABLE public.item_colors   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_sizes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_variants ENABLE ROW LEVEL SECURITY;

-- 色とサイズは表示に必要なので、published 商品のものだけ公開する。
-- ポリシー内で join せず、IN + サブクエリにする（Supabase の RLS パフォーマンス推奨）。
CREATE POLICY "public read colors of published items" ON public.item_colors
  FOR SELECT TO anon, authenticated
  USING (item_id IN (SELECT id FROM public.items WHERE status = 'published'));

CREATE POLICY "public read sizes of published items" ON public.item_sizes
  FOR SELECT TO anon, authenticated
  USING (item_id IN (SELECT id FROM public.items WHERE status = 'published'));

-- 在庫の実数は業務データなので、クライアントからは一切読ませない。
-- 公開 API は service role で読み、在庫の有無だけに変換して返す。
CREATE POLICY "deny direct client access" ON public.item_variants
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);

-- このプロジェクトの Supabase は public スキーマの新規テーブルに anon / authenticated へ
-- 全権限を自動付与するため、まず剥がしてから必要な権限だけを付け直す。
-- RESTRICTIVE ポリシーだけに頼ると、将来 PERMISSIVE ポリシーが 1 本足された時点で開いてしまう。
REVOKE ALL ON public.item_colors   FROM anon, authenticated;
REVOKE ALL ON public.item_sizes    FROM anon, authenticated;
REVOKE ALL ON public.item_variants FROM anon, authenticated;

GRANT SELECT ON public.item_colors TO anon, authenticated;
GRANT SELECT ON public.item_sizes  TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_colors, public.item_sizes, public.item_variants TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.item_colors_id_seq, public.item_sizes_id_seq, public.item_variants_id_seq TO service_role;

COMMIT;
